apiVersion: batch/v1
kind: CronJob
metadata:
  name: cw-cron
spec:
  schedule: "*/2 * * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    metadata:
      labels:
        cron-name: cw-cron
    spec:
      template:
        metadata:
          labels:
            cron-name: cw-cron
        spec:
          restartPolicy: OnFailure
          containers:
          - name: cw-base
            image: enfasis2w1q/cw-base
            imagePullPolicy: Always
            env:
              - name: DATABASE_URL
                value: psql://user:secret@postgres:5432/base
            command: ["/bin/sh", "-c"]
            args: ["python manage.py upload_daily_ranking; python manage.py create_dummy_data; echo finish"]
