#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

python manage.py collectstatic --noinput

gunicorn wsgi \
    --bind 0.0.0.0:5000 \
    --chdir=/app/quizes \
    --workers $GUNICORN_WORKERS \
    --threads $GUNICORN_THREADS
