name: Django CI

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: demo
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push Base Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          file: deploy/Dockerfile
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/cw-base
      - name: Build and push Test Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          file: deploy/Dockerfile
          target: testing
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/cw-testing
